### ISSUE TITLE
Click event listener needs to be re-launched, after renewing the list of available commands

### ISSUE THREAD

**Issue by jtsimoes** [peci-g3/drag-and-drop-mission-construction#2]
The click event listener does not listen for the new renewed go-to commands, resulting in the map pop-up only opening when clicking on the `<input>` of the first added go-to command, when loading the page.

It is necessary to re-launch this event listener each time the commands in the list of available commands are renewed.

![testing](https://user-images.githubusercontent.com/34691647/168493790-a8345f6b-0039-4763-8d26-dd7307ae21ff.gif)

**Comment by jtsimoes** [comment]
@digas99 Estavas a sugerir colocar só `document.addEventListener('click', function (e) { ... }` sem o selector, era isso? E fazer a verificação do `target` com um `if` dentro da função?
https://github.com/peci-g3/mission-generator/blob/c14c2329b81d771e8e3cae51433be873e0ce5d21/script.js#L288

**Comment by digas99** [comment]
Algo do género:
```
document.addEventListener('click', e => {
   if (e.target.classList.contains('go-to')) {
      // do something
   }
});
```
